In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv('cal_housing_clean.csv')

In [4]:
df.head()

housingMedianAge  totalRooms  totalBedrooms  population  households  \
0              41.0       880.0          129.0       322.0       126.0   
1              21.0      7099.0         1106.0      2401.0      1138.0   
2              52.0      1467.0          190.0       496.0       177.0   
3              52.0      1274.0          235.0       558.0       219.0   
4              52.0      1627.0          280.0       565.0       259.0   

   medianIncome  medianHouseValue  
0        8.3252          452600.0  
1        8.3014          358500.0  
2        7.2574          352100.0  
3        5.6431          341300.0  
4        3.8462          342200.0

In [5]:
df.describe()

housingMedianAge    totalRooms  totalBedrooms    population  \
count      20640.000000  20640.000000   20640.000000  20640.000000   
mean          28.639486   2635.763081     537.898014   1425.476744   
std           12.585558   2181.615252     421.247906   1132.462122   
min            1.000000      2.000000       1.000000      3.000000   
25%           18.000000   1447.750000     295.000000    787.000000   
50%           29.000000   2127.000000     435.000000   1166.000000   
75%           37.000000   3148.000000     647.000000   1725.000000   
max           52.000000  39320.000000    6445.000000  35682.000000   

         households  medianIncome  medianHouseValue  
count  20640.000000  20640.000000      20640.000000  
mean     499.539680      3.870671     206855.816909  
std      382.329753      1.899822     115395.615874  
min        1.000000      0.499900      14999.000000  
25%      280.000000      2.563400     119600.000000  
50%      409.000000      3.534800     179700.000000  
75%      605.000000      4.743250     264725.000000  
max     6082.000000     15.000100     500001.000000

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
df.columns

Index(['housingMedianAge', 'totalRooms', 'totalBedrooms', 'population',
       'households', 'medianIncome', 'medianHouseValue'],
      dtype='object')

In [11]:
x_data = df[['housingMedianAge', 'totalRooms', 'totalBedrooms', 'population',
       'households', 'medianIncome']]
y_values = df[['medianHouseValue']]

In [12]:
x_data.head()

housingMedianAge  totalRooms  totalBedrooms  population  households  \
0              41.0       880.0          129.0       322.0       126.0   
1              21.0      7099.0         1106.0      2401.0      1138.0   
2              52.0      1467.0          190.0       496.0       177.0   
3              52.0      1274.0          235.0       558.0       219.0   
4              52.0      1627.0          280.0       565.0       259.0   

   medianIncome  
0        8.3252  
1        8.3014  
2        7.2574  
3        5.6431  
4        3.8462

In [13]:
y_values.head()

medianHouseValue
0          452600.0
1          358500.0
2          352100.0
3          341300.0
4          342200.0

In [27]:
X_train, X_eval, y_train, y_eval = train_test_split(x_data, y_values, test_size=0.3, random_state=101)

In [15]:
from sklearn.preprocessing import MinMaxScaler

In [16]:
scaler = MinMaxScaler()

In [17]:
scaler.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [18]:
X_train = pd.DataFrame(data = scaler.transform(X_train), columns = X_train.columns, index = X_train.index)

In [19]:
X_train.head()

housingMedianAge  totalRooms  totalBedrooms  population  households  \
6761          0.352941    0.069688       0.117163    0.048769    0.115442   
3010          0.607843    0.011242       0.015673    0.008367    0.014142   
7812          0.666667    0.025230       0.031347    0.020971    0.030258   
8480          0.666667    0.032530       0.033830    0.024752    0.030094   
1051          0.294118    0.031919       0.035692    0.019466    0.034863   

      medianIncome  
6761      0.142508  
3010      0.045027  
7812      0.212866  
8480      0.298651  
1051      0.272631

In [20]:
X_test = pd.DataFrame(data = scaler.transform(X_train), columns = X_train.columns, index = X_train.index)

In [21]:
df.columns

Index(['housingMedianAge', 'totalRooms', 'totalBedrooms', 'population',
       'households', 'medianIncome', 'medianHouseValue'],
      dtype='object')

In [24]:
husing_age = tf.feature_column.numeric_column('housingMedianAge')
tot_rooms = tf.feature_column.numeric_column('totalRooms')
tot_bedrms = tf.feature_column.numeric_column('totalBedrooms')
pop = tf.feature_column.numeric_column('population')
households = tf.feature_column.numeric_column('households')
mednincom = tf.feature_column.numeric_column('medianIncome')

In [25]:
feat_colms = [husing_age, tot_rooms, tot_bedrms, pop, households, mednincom]

In [30]:
input_func = tf.estimator.inputs.pandas_input_fn(x = X_train, y = y_train, batch_size = 10, num_epochs = 1000, shuffle = True)

In [31]:
dnn_model = tf.estimator.DNNRegressor(hidden_units = [6, 6, 6], feature_columns = feat_colms)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\sony\\AppData\\Local\\Temp\\tmpaaa53fb5', '_tf_random_seed': 1, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_save_checkpoints_steps': None, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100}


In [32]:
dnn_model.train(input_fn = input_func, steps = 1000)

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into C:\Users\sony\AppData\Local\Temp\tmpaaa53fb5\model.ckpt.
INFO:tensorflow:loss = 578725500000.0, step = 1
INFO:tensorflow:global_step/sec: 412.349
INFO:tensorflow:loss = 359630240000.0, step = 101 (0.246 sec)
INFO:tensorflow:global_step/sec: 427.37
INFO:tensorflow:loss = 61782280000.0, step = 201 (0.234 sec)
INFO:tensorflow:global_step/sec: 423.507
INFO:tensorflow:loss = 208665310000.0, step = 301 (0.236 sec)
INFO:tensorflow:global_step/sec: 433.028
INFO:tensorflow:loss = 511479250000.0, step = 401 (0.231 sec)
INFO:tensorflow:global_step/sec: 417.142
INFO:tensorflow:loss = 174564330000.0, step = 501 (0.245 sec)
INFO:tensorflow:global_step/sec: 401.603
INFO:tensorflow:loss = 357606620000.0, step = 601 (0.244 sec)
INFO:tensorflow:global_step/sec: 403.581
INFO:tensorflow:loss = 198967300000.0, step = 701 (0.248 sec)
INFO:tensorflow:global_step/sec: 385.424
INFO:tensorflow:loss = 356168100000.0, step =

In [33]:
eval_input_func = tf.estimator.inputs.pandas_input_fn(x=X_eval, y=y_eval, batch_size=10, num_epochs=1000, shuffle=False)

In [34]:
dnn_model.evaluate(input_fn = eval_input_func, steps = 1000)

INFO:tensorflow:Starting evaluation at 2018-02-27-01:09:35
INFO:tensorflow:Restoring parameters from C:\Users\sony\AppData\Local\Temp\tmpaaa53fb5\model.ckpt-1000
INFO:tensorflow:Evaluation [1/1000]
INFO:tensorflow:Evaluation [2/1000]
INFO:tensorflow:Evaluation [3/1000]
INFO:tensorflow:Evaluation [4/1000]
INFO:tensorflow:Evaluation [5/1000]
INFO:tensorflow:Evaluation [6/1000]
INFO:tensorflow:Evaluation [7/1000]
INFO:tensorflow:Evaluation [8/1000]
INFO:tensorflow:Evaluation [9/1000]
INFO:tensorflow:Evaluation [10/1000]
INFO:tensorflow:Evaluation [11/1000]
INFO:tensorflow:Evaluation [12/1000]
INFO:tensorflow:Evaluation [13/1000]
INFO:tensorflow:Evaluation [14/1000]
INFO:tensorflow:Evaluation [15/1000]
INFO:tensorflow:Evaluation [16/1000]
INFO:tensorflow:Evaluation [17/1000]
INFO:tensorflow:Evaluation [18/1000]
INFO:tensorflow:Evaluation [19/1000]
INFO:tensorflow:Evaluation [20/1000]
INFO:tensorflow:Evaluation [21/1000]
INFO:tensorflow:Evaluation [22/1000]
INFO:tensorflow:Evaluation [23/10

INFO:tensorflow:Evaluation [216/1000]
INFO:tensorflow:Evaluation [217/1000]
INFO:tensorflow:Evaluation [218/1000]
INFO:tensorflow:Evaluation [219/1000]
INFO:tensorflow:Evaluation [220/1000]
INFO:tensorflow:Evaluation [221/1000]
INFO:tensorflow:Evaluation [222/1000]
INFO:tensorflow:Evaluation [223/1000]
INFO:tensorflow:Evaluation [224/1000]
INFO:tensorflow:Evaluation [225/1000]
INFO:tensorflow:Evaluation [226/1000]
INFO:tensorflow:Evaluation [227/1000]
INFO:tensorflow:Evaluation [228/1000]
INFO:tensorflow:Evaluation [229/1000]
INFO:tensorflow:Evaluation [230/1000]
INFO:tensorflow:Evaluation [231/1000]
INFO:tensorflow:Evaluation [232/1000]
INFO:tensorflow:Evaluation [233/1000]
INFO:tensorflow:Evaluation [234/1000]
INFO:tensorflow:Evaluation [235/1000]
INFO:tensorflow:Evaluation [236/1000]
INFO:tensorflow:Evaluation [237/1000]
INFO:tensorflow:Evaluation [238/1000]
INFO:tensorflow:Evaluation [239/1000]
INFO:tensorflow:Evaluation [240/1000]
INFO:tensorflow:Evaluation [241/1000]
INFO:tensorf

INFO:tensorflow:Evaluation [432/1000]
INFO:tensorflow:Evaluation [433/1000]
INFO:tensorflow:Evaluation [434/1000]
INFO:tensorflow:Evaluation [435/1000]
INFO:tensorflow:Evaluation [436/1000]
INFO:tensorflow:Evaluation [437/1000]
INFO:tensorflow:Evaluation [438/1000]
INFO:tensorflow:Evaluation [439/1000]
INFO:tensorflow:Evaluation [440/1000]
INFO:tensorflow:Evaluation [441/1000]
INFO:tensorflow:Evaluation [442/1000]
INFO:tensorflow:Evaluation [443/1000]
INFO:tensorflow:Evaluation [444/1000]
INFO:tensorflow:Evaluation [445/1000]
INFO:tensorflow:Evaluation [446/1000]
INFO:tensorflow:Evaluation [447/1000]
INFO:tensorflow:Evaluation [448/1000]
INFO:tensorflow:Evaluation [449/1000]
INFO:tensorflow:Evaluation [450/1000]
INFO:tensorflow:Evaluation [451/1000]
INFO:tensorflow:Evaluation [452/1000]
INFO:tensorflow:Evaluation [453/1000]
INFO:tensorflow:Evaluation [454/1000]
INFO:tensorflow:Evaluation [455/1000]
INFO:tensorflow:Evaluation [456/1000]
INFO:tensorflow:Evaluation [457/1000]
INFO:tensorf

INFO:tensorflow:Evaluation [648/1000]
INFO:tensorflow:Evaluation [649/1000]
INFO:tensorflow:Evaluation [650/1000]
INFO:tensorflow:Evaluation [651/1000]
INFO:tensorflow:Evaluation [652/1000]
INFO:tensorflow:Evaluation [653/1000]
INFO:tensorflow:Evaluation [654/1000]
INFO:tensorflow:Evaluation [655/1000]
INFO:tensorflow:Evaluation [656/1000]
INFO:tensorflow:Evaluation [657/1000]
INFO:tensorflow:Evaluation [658/1000]
INFO:tensorflow:Evaluation [659/1000]
INFO:tensorflow:Evaluation [660/1000]
INFO:tensorflow:Evaluation [661/1000]
INFO:tensorflow:Evaluation [662/1000]
INFO:tensorflow:Evaluation [663/1000]
INFO:tensorflow:Evaluation [664/1000]
INFO:tensorflow:Evaluation [665/1000]
INFO:tensorflow:Evaluation [666/1000]
INFO:tensorflow:Evaluation [667/1000]
INFO:tensorflow:Evaluation [668/1000]
INFO:tensorflow:Evaluation [669/1000]
INFO:tensorflow:Evaluation [670/1000]
INFO:tensorflow:Evaluation [671/1000]
INFO:tensorflow:Evaluation [672/1000]
INFO:tensorflow:Evaluation [673/1000]
INFO:tensorf

INFO:tensorflow:Evaluation [864/1000]
INFO:tensorflow:Evaluation [865/1000]
INFO:tensorflow:Evaluation [866/1000]
INFO:tensorflow:Evaluation [867/1000]
INFO:tensorflow:Evaluation [868/1000]
INFO:tensorflow:Evaluation [869/1000]
INFO:tensorflow:Evaluation [870/1000]
INFO:tensorflow:Evaluation [871/1000]
INFO:tensorflow:Evaluation [872/1000]
INFO:tensorflow:Evaluation [873/1000]
INFO:tensorflow:Evaluation [874/1000]
INFO:tensorflow:Evaluation [875/1000]
INFO:tensorflow:Evaluation [876/1000]
INFO:tensorflow:Evaluation [877/1000]
INFO:tensorflow:Evaluation [878/1000]
INFO:tensorflow:Evaluation [879/1000]
INFO:tensorflow:Evaluation [880/1000]
INFO:tensorflow:Evaluation [881/1000]
INFO:tensorflow:Evaluation [882/1000]
INFO:tensorflow:Evaluation [883/1000]
INFO:tensorflow:Evaluation [884/1000]
INFO:tensorflow:Evaluation [885/1000]
INFO:tensorflow:Evaluation [886/1000]
INFO:tensorflow:Evaluation [887/1000]
INFO:tensorflow:Evaluation [888/1000]
INFO:tensorflow:Evaluation [889/1000]
INFO:tensorf

{'average_loss': 27333521000.0, 'global_step': 1000, 'loss': 273335200000.0}

In [36]:
pred_input_func = tf.estimator.inputs.pandas_input_fn(x=X_eval, batch_size=10, num_epochs=1, shuffle=False)

In [37]:
dnn_model.predict(input_fn=pred_input_func)

<generator object Estimator.predict at 0x0000029DE6B3D990>

In [40]:
predictions = list(dnn_model.predict(input_fn = pred_input_func))

INFO:tensorflow:Restoring parameters from C:\Users\sony\AppData\Local\Temp\tmpaaa53fb5\model.ckpt-1000


In [41]:
predictions

[{'predictions': array([74325.88], dtype=float32)},
 {'predictions': array([42906.773], dtype=float32)},
 {'predictions': array([66019.95], dtype=float32)},
 {'predictions': array([72628.72], dtype=float32)},
 {'predictions': array([129231.805], dtype=float32)},
 {'predictions': array([174676.03], dtype=float32)},
 {'predictions': array([101051.05], dtype=float32)},
 {'predictions': array([91098.5], dtype=float32)},
 {'predictions': array([92336.67], dtype=float32)},
 {'predictions': array([4362.272], dtype=float32)},
 {'predictions': array([117622.055], dtype=float32)},
 {'predictions': array([245110.95], dtype=float32)},
 {'predictions': array([79332.836], dtype=float32)},
 {'predictions': array([48809.414], dtype=float32)},
 {'predictions': array([98671.92], dtype=float32)},
 {'predictions': array([32473.156], dtype=float32)},
 {'predictions': array([35664.957], dtype=float32)},
 {'predictions': array([104437.125], dtype=float32)},
 {'predictions': array([153474.2], dtype=float32)},

In [42]:
final_pred = []
for pred in predictions:
    final_pred.append(pred['predictions'])

In [43]:
final_pred

[array([74325.88], dtype=float32),
 array([42906.773], dtype=float32),
 array([66019.95], dtype=float32),
 array([72628.72], dtype=float32),
 array([129231.805], dtype=float32),
 array([174676.03], dtype=float32),
 array([101051.05], dtype=float32),
 array([91098.5], dtype=float32),
 array([92336.67], dtype=float32),
 array([4362.272], dtype=float32),
 array([117622.055], dtype=float32),
 array([245110.95], dtype=float32),
 array([79332.836], dtype=float32),
 array([48809.414], dtype=float32),
 array([98671.92], dtype=float32),
 array([32473.156], dtype=float32),
 array([35664.957], dtype=float32),
 array([104437.125], dtype=float32),
 array([153474.2], dtype=float32),
 array([88566.6], dtype=float32),
 array([141808.02], dtype=float32),
 array([308288.12], dtype=float32),
 array([177694.78], dtype=float32),
 array([70631.375], dtype=float32),
 array([132429.44], dtype=float32),
 array([83695.14], dtype=float32),
 array([143734.44], dtype=float32),
 array([56156.953], dtype=float32),
 

In [44]:
from sklearn.metrics import mean_squared_error

In [46]:
mean_squared_error(y_eval, final_pred)**0.5

165109.19098587052